Adds support for User-Agent string
allthingstalk/python-sdk pull request #6
Opened 2018-05-16 09:46 UTC by rayalex

2018-05-16 09:50 UTC, vydd requested changes
Just minor stuff; looks good otherwise!

2018-05-16 09:50 UTC, vydd commented on allthingstalk/clients.py
> +        self._version = self.__get_version()
thanks!

2018-05-16 09:50 UTC, vydd commented on allthingstalk/clients.py
> +    def __get_version(self):
Why is the underscore here doubled?

2018-05-16 09:50 UTC, vydd commented on allthingstalk/clients.py
> +                                    headers=self._get_headers(),
weird spacing

2018-05-16 09:56 UTC, rayalex commented
@vydd Can you re-check please?

2018-05-16 10:00 UTC, vydd approved these changes

2018-05-16 10:02 UTC, vydd commented
Cool, have you tested it with a simple example? If so, feel free to merge and push the package to PyPI (or I can, if it's too much of a hassle).

2018-05-17 07:36 UTC, rayalex commented
@vydd I have. I'll try out other examples and close this PR if everything passes.

2018-05-17 09:20 UTC, rayalex commented
@vydd Works as expected.

2018-05-17 09:20 UTC, merged